# Generated by Django 4.2 on 2025-04-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_order_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={"verbose_name_plural": "Menu Items"},
        ),
        migrations.AlterModelOptions(
            name="userorder",
            options={"verbose_name": "Orders", "verbose_name_plural": "Orders"},
        ),
        migrations.AddField(
            model_name="school",
            name="pizza_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of weekdays when pizza is served (e.g. ["mon", "wed"])',
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="delivery_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cold Only", "Cold Only"),
                    ("Ready to Serve", "Ready to Serve"),
                    ("Heat on Site", "Heat on Site"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
