# Generated by Django 4.2 on 2025-04-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "food_order_api",
            "0002_alter_customuser_options_alter_menuitem_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="delivery_schedule",
        ),
        migrations.RemoveField(
            model_name="school",
            name="delivery_schedule",
        ),
        migrations.AddField(
            model_name="school",
            name="delivery_schedule",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Days this school receives delivery (e.g. ["mon", "tue"])',
            ),
        ),
    ]
