# Generated by Django 4.2 on 2025-04-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_order_api", "0004_customuser_delivery_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="family_style_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Days for Family Style service (e.g. ["mon", "wed"])',
            ),
        ),
    ]
