# Generated by Django 4.2 on 2025-04-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_order_api", "0006_userprofile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
