# Generated by Django 5.1.7 on 2025-03-08 06:18

import django.db.models.deletion
import food_order_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LunchProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NSLP K-8', 'NSLP K-8'), ('NSLP 9-12', 'NSLP 9-12'), ('CACFP K-12', 'CACFP K-12'), ('CACFP Pre-K', 'CACFP Pre-K'), ('CACFP Adults', 'CACFP Adults')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatePortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Protein', 'Protein'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Grain', 'Grain'), ('Dairy', 'Dairy')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='food_order_api.foodtype')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Hot Meal', 'Hot Meal'), ('Hot Vegetarian', 'Hot Vegetarian'), ('Cold Meal', 'Cold Meal'), ('Cold Pastas', 'Cold Pastas'), ('Cold Vegetarian', 'Cold Vegetarian'), ('Daily Salad', 'Daily Salad'), ('Snack', 'Snack')], max_length=50)),
                ('is_new', models.BooleanField(default=False)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', validators=[food_order_api.models.validate_image_extension])),
                ('lunch_programs', models.ManyToManyField(blank=True, to='food_order_api.lunchprogram')),
                ('plate_portions', models.ManyToManyField(blank=True, to='food_order_api.plateportion')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='food_order_api.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_order_api.menuitem')),
            ],
            options={
                'unique_together': {('user', 'menu_item')},
            },
        ),
    ]
