# Generated by Django 5.1.7 on 2025-03-11 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='ordered_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='items',
            new_name='menu_items',
        ),
        migrations.AddField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Received', 'Order Received'), ('Paid', 'Paid'), ('Manufactured', 'Manufactured'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
