# Generated by Django 4.2 on 2025-03-19 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_order_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSupportProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("extension", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="support_profiles/"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="support_rep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_users",
                to="food_order_api.customersupportprofile",
            ),
        ),
    ]
