# Generated by Django 5.1.7 on 2025-03-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order_api', '0002_rename_ordered_on_userorder_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
