# Generated by Django 4.2 on 2025-03-19 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food_order_api", "0003_customuser_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_schedule",
                    models.ManyToManyField(
                        blank=True,
                        related_name="users",
                        to="food_order_api.deliveryschedule",
                    ),
                ),
                (
                    "lunch_programs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="users",
                        to="food_order_api.lunchprogram",
                    ),
                ),
                (
                    "support_rep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_users",
                        to="food_order_api.customersupportprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
