# Generated by Django 5.1.7 on 2025-03-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order_api', '0004_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userorder',
            options={'verbose_name': 'Customer Orders', 'verbose_name_plural': 'Customer Orders'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
