# Generated by Django 4.2 on 2025-03-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_order_api", "0005_customuser_route_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="route_number",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="route_number",
            field=models.CharField(
                blank=True,
                help_text="Enter a 2-digit route number",
                max_length=2,
                null=True,
            ),
        ),
    ]
