# Generated by Django 4.2 on 2025-03-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_order_api", "0006_remove_customuser_route_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="additional_notes",
            field=models.TextField(
                blank=True, help_text="Enter any additional notes.", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="delivery_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ready to Serve", "Ready to Serve"),
                    ("Heat on Site", "Heat on Site"),
                ],
                help_text="Select the delivery type.",
                max_length=20,
                null=True,
            ),
        ),
    ]
