# Generated by Django 4.2 on 2025-03-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_order_api", "0007_userprofile_additional_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="delivery_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
