# Generated by Django 4.2 on 2025-04-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_order_api", "0007_alter_userprofile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
    ]
