# Generated by Django 4.2 on 2025-03-21 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0014_remove_user_support_rep"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food_order_api", "0008_orderitem_delivery_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="auth.group",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="schools", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
