# Generated by Django 4.2 on 2025-03-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_order_api", "0009_school"),
    ]

    operations = [
        migrations.DeleteModel(
            name="School",
        ),
    ]
