# Generated by Django 4.2 on 2025-03-21 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0016_delete_school"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food_order_api", "0010_delete_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="delivery_schedule",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="delivery_type",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="lunch_programs",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="route_number",
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "route_number",
                    models.CharField(
                        blank=True,
                        help_text="Enter a 2-digit route number",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ready to Serve", "Ready to Serve"),
                            ("Heat on Site", "Heat on Site"),
                        ],
                        help_text="Select the delivery type.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "delivery_schedule",
                    models.ManyToManyField(
                        blank=True, to="food_order_api.deliveryschedule"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="auth.group",
                    ),
                ),
                (
                    "lunch_programs",
                    models.ManyToManyField(
                        blank=True, to="food_order_api.lunchprogram"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="schools", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schools",
            },
        ),
    ]
