# Generated by Django 4.2 on 2025-03-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_order_api", "0011_remove_userprofile_delivery_schedule_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="School",
        ),
    ]
