# Generated by Django 4.2 on 2025-03-21 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0017_school"),
        ("food_order_api", "0012_delete_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorder",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="auth.school",
            ),
        ),
    ]
